add support for cilium cni plugin
syseleven/terraform-provider-metakube pull request #84
Opened 2023-12-14 12:29 UTC by nrobert13

2023-12-14 15:33 UTC, squ94wk requested changes

2023-12-14 15:33 UTC, squ94wk commented on Makefile
> -# METAKUBE_OPENSTACK_APPLICATION_CREDENTIALS_SECRET
Why do we remove these?

2023-12-14 15:33 UTC, squ94wk commented on metakube/resource_cluster_test.go
> +		{{end}}
Just keep the usual whitespace:
```suggestion
		{{ if .CNIPlugin }}
		cni_plugin {
			type = "{{ .CNIPlugin }}"
		  }
		{{ end }}
```

2024-01-02 16:28 UTC, merged

2024-01-03 09:46 UTC, phiphi282 commented
Why did this get merged with the commented lines? They shouldn't be commented out